[package]
name = "ledger-hackathon-rust-anims"
version = "0.1.0"
authors = ["Gaëtan Renaudeau <renaudeau.gaetan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.17"
